[package]
name = "guessing_game_by_mirz"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A fun game where you guess what number the computer ha chosen."

[dependencies]
rand = "0.8.5"
